import type { NextPage } from 'next'
import { useRef, useEffect } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as Fabric from '../../node_modules/fabric'
import * as ImageMarkup from '../../ImageMarkupBuilder.js'

const Canvas = (props) => {
   const canvasRef = useRef(null);

   useEffect(() => {
     const canvas = canvasRef.current;
     const fabric = new Fabric.fabric.Canvas(canvasRef.current, {
      hoverCursor: 'pointer',
      moveCursor: 'move',
      defaultCursor: 'crosshair',

     });
     ImageMarkup.Builder(fabric);
   }, []);

   return (
      <>
         <canvas ref={canvasRef} className={styles.canvas} />
      </>
   );
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>ImageMarkup Demo</h1>
        <Canvas />
         
      </main>
    </div>
  )
}

export default Home
